# ByteCore Configuration

# Shop Settings
shops:
  allowed-containers:
    - BARREL
  enabled-by-default: BARREL
  protection-radius: 0

# Location Settings
locations:
  max-per-player: 3

# Server Information
server:
  name: "bytefi.sh"
  website: "https://bytefi.sh/mc"

# API Settings
api:
  port: 25578

# Server Rules
rules:
  - "Do not steal, destroy or attack people/pets unprovoked."
  - "Do not use any hacks or client modifications that would give you an unfair advantage."
  - "No vulgar or obscene language in the chat."
